#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("QuickShare.Droid.Resource", IsApplication=true)]

namespace QuickShare.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::QuickShare.Droid.RomeComponent.Resource.String.ApplicationName = global::QuickShare.Droid.Resource.String.ApplicationName;
			global::QuickShare.Droid.RomeComponent.Resource.String.Hello = global::QuickShare.Droid.Resource.String.Hello;
			global::QuickShare.Droid.WebServerComponent.Resource.String.ApplicationName = global::QuickShare.Droid.Resource.String.ApplicationName;
			global::QuickShare.Droid.WebServerComponent.Resource.String.Hello = global::QuickShare.Droid.Resource.String.Hello;
			global::PCLStorage.Resource.String.ApplicationName = global::QuickShare.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::QuickShare.Droid.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int marked_item_animation = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int unmarked_item_animation = 2131034113;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int error_dir = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int extensions = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int offset_dir = 2130771972;
			
			// aapt resource value: 0x7f010002
			public const int root_dir = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int selection_mode = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int selection_type = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int title_text = 2130771974;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080000
			public const int colorAccent = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int colorHeader = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int colorPrimary = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int colorPrimaryDark = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int textColorPrimary = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int textColorSecondary = 2131230725;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int activity_margin = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int toolbar_image_margin = 2131165185;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bottom_shadow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090016
			public const int button3 = 2131296278;
			
			// aapt resource value: 0x7f09000a
			public const int cancel = 2131296266;
			
			// aapt resource value: 0x7f09000f
			public const int dir_path = 2131296271;
			
			// aapt resource value: 0x7f090002
			public const int dir_select = 2131296258;
			
			// aapt resource value: 0x7f09000d
			public const int dname = 2131296269;
			
			// aapt resource value: 0x7f090011
			public const int fileList = 2131296273;
			
			// aapt resource value: 0x7f090003
			public const int file_dir_select = 2131296259;
			
			// aapt resource value: 0x7f090008
			public const int file_mark = 2131296264;
			
			// aapt resource value: 0x7f090004
			public const int file_select = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int fname = 2131296262;
			
			// aapt resource value: 0x7f090012
			public const int footer = 2131296274;
			
			// aapt resource value: 0x7f090007
			public const int ftype = 2131296263;
			
			// aapt resource value: 0x7f090010
			public const int header = 2131296272;
			
			// aapt resource value: 0x7f09000c
			public const int imageView = 2131296268;
			
			// aapt resource value: 0x7f090005
			public const int image_type = 2131296261;
			
			// aapt resource value: 0x7f090009
			public const int linearLayout = 2131296265;
			
			// aapt resource value: 0x7f09001a
			public const int listView1 = 2131296282;
			
			// aapt resource value: 0x7f090015
			public const int mainSendClipboard = 2131296277;
			
			// aapt resource value: 0x7f090013
			public const int mainSendFile = 2131296275;
			
			// aapt resource value: 0x7f090014
			public const int mainSendPicture = 2131296276;
			
			// aapt resource value: 0x7f090000
			public const int multi_mode = 2131296256;
			
			// aapt resource value: 0x7f09001d
			public const int previewImageView = 2131296285;
			
			// aapt resource value: 0x7f09000b
			public const int select = 2131296267;
			
			// aapt resource value: 0x7f090018
			public const int selectedDeviceName = 2131296280;
			
			// aapt resource value: 0x7f09001c
			public const int sendProgress = 2131296284;
			
			// aapt resource value: 0x7f09001b
			public const int sendStatus = 2131296283;
			
			// aapt resource value: 0x7f090001
			public const int single_mode = 2131296257;
			
			// aapt resource value: 0x7f090019
			public const int textView1 = 2131296281;
			
			// aapt resource value: 0x7f090017
			public const int textView2 = 2131296279;
			
			// aapt resource value: 0x7f09000e
			public const int title = 2131296270;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int dialog_file_list = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int dialog_file_list_item = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int dialog_footer = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int dialog_header = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int dialog_main = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Main = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int SendPage = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_directory_parent = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_type_file = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_type_folder = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int cancel_button_label = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int choose_button_label = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int default_dir = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int error_dir_access = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int label_parent_dir = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int label_parent_directory = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int last_edit = 2131099653;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FilePickerPreference = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 3
			public const int FilePickerPreference_error_dir = 3;
			
			// aapt resource value: 5
			public const int FilePickerPreference_extensions = 5;
			
			// aapt resource value: 4
			public const int FilePickerPreference_offset_dir = 4;
			
			// aapt resource value: 2
			public const int FilePickerPreference_root_dir = 2;
			
			// aapt resource value: 0
			public const int FilePickerPreference_selection_mode = 0;
			
			// aapt resource value: 1
			public const int FilePickerPreference_selection_type = 1;
			
			// aapt resource value: 6
			public const int FilePickerPreference_title_text = 6;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
