#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("QuickShare.Droid.Resource", IsApplication=true)]

namespace QuickShare.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::QuickShare.Droid.RomeComponent.Resource.String.ApplicationName = global::QuickShare.Droid.Resource.String.ApplicationName;
			global::QuickShare.Droid.RomeComponent.Resource.String.Hello = global::QuickShare.Droid.Resource.String.Hello;
			global::QuickShare.Droid.WebServerComponent.Resource.String.ApplicationName = global::QuickShare.Droid.Resource.String.ApplicationName;
			global::QuickShare.Droid.WebServerComponent.Resource.String.Hello = global::QuickShare.Droid.Resource.String.Hello;
			global::PCLStorage.Resource.String.ApplicationName = global::QuickShare.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::QuickShare.Droid.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int marked_item_animation = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int unmarked_item_animation = 2131034113;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int error_dir = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int extensions = 2130771976;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010007
			public const int offset_dir = 2130771975;
			
			// aapt resource value: 0x7f010005
			public const int root_dir = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int selection_mode = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int selection_type = 2130771972;
			
			// aapt resource value: 0x7f010009
			public const int title_text = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f090000
			public const int colorAccent = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int colorHeader = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int colorPrimary = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int colorPrimaryDark = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int textColorPrimary = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int textColorSecondary = 2131296261;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int activity_margin = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int toolbar_image_margin = 2131230721;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bottom_shadow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0000
			public const int adjust_height = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int adjust_width = 2131361793;
			
			// aapt resource value: 0x7f0a0019
			public const int button3 = 2131361817;
			
			// aapt resource value: 0x7f0a000d
			public const int cancel = 2131361805;
			
			// aapt resource value: 0x7f0a0012
			public const int dir_path = 2131361810;
			
			// aapt resource value: 0x7f0a0005
			public const int dir_select = 2131361797;
			
			// aapt resource value: 0x7f0a0010
			public const int dname = 2131361808;
			
			// aapt resource value: 0x7f0a0014
			public const int fileList = 2131361812;
			
			// aapt resource value: 0x7f0a0006
			public const int file_dir_select = 2131361798;
			
			// aapt resource value: 0x7f0a000b
			public const int file_mark = 2131361803;
			
			// aapt resource value: 0x7f0a0007
			public const int file_select = 2131361799;
			
			// aapt resource value: 0x7f0a0009
			public const int fname = 2131361801;
			
			// aapt resource value: 0x7f0a0015
			public const int footer = 2131361813;
			
			// aapt resource value: 0x7f0a000a
			public const int ftype = 2131361802;
			
			// aapt resource value: 0x7f0a0013
			public const int header = 2131361811;
			
			// aapt resource value: 0x7f0a000f
			public const int imageView = 2131361807;
			
			// aapt resource value: 0x7f0a0008
			public const int image_type = 2131361800;
			
			// aapt resource value: 0x7f0a000c
			public const int linearLayout = 2131361804;
			
			// aapt resource value: 0x7f0a001e
			public const int listView1 = 2131361822;
			
			// aapt resource value: 0x7f0a0018
			public const int mainSendClipboard = 2131361816;
			
			// aapt resource value: 0x7f0a0016
			public const int mainSendFile = 2131361814;
			
			// aapt resource value: 0x7f0a001a
			public const int mainSendMessageCarrier = 2131361818;
			
			// aapt resource value: 0x7f0a0017
			public const int mainSendPicture = 2131361815;
			
			// aapt resource value: 0x7f0a0003
			public const int multi_mode = 2131361795;
			
			// aapt resource value: 0x7f0a0002
			public const int none = 2131361794;
			
			// aapt resource value: 0x7f0a0021
			public const int previewImageView = 2131361825;
			
			// aapt resource value: 0x7f0a000e
			public const int select = 2131361806;
			
			// aapt resource value: 0x7f0a001c
			public const int selectedDeviceName = 2131361820;
			
			// aapt resource value: 0x7f0a0020
			public const int sendProgress = 2131361824;
			
			// aapt resource value: 0x7f0a001f
			public const int sendStatus = 2131361823;
			
			// aapt resource value: 0x7f0a0004
			public const int single_mode = 2131361796;
			
			// aapt resource value: 0x7f0a001d
			public const int textView1 = 2131361821;
			
			// aapt resource value: 0x7f0a001b
			public const int textView2 = 2131361819;
			
			// aapt resource value: 0x7f0a0011
			public const int title = 2131361809;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int dialog_file_list = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int dialog_file_list_item = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int dialog_footer = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int dialog_header = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int dialog_main = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Main = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int SendPage = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_directory_parent = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_type_file = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_type_folder = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070002
			public const int ApplicationName = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int Hello = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int cancel_button_label = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int choose_button_label = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int common_google_play_services_unknown_issue = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int default_dir = 2131165191;
			
			// aapt resource value: 0x7f07000c
			public const int default_web_client_id = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int error_dir_access = 2131165192;
			
			// aapt resource value: 0x7f07000d
			public const int firebase_database_url = 2131165197;
			
			// aapt resource value: 0x7f07000a
			public const int gcm_defaultSenderId = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int google_api_key = 2131165198;
			
			// aapt resource value: 0x7f07000b
			public const int google_app_id = 2131165195;
			
			// aapt resource value: 0x7f07000f
			public const int google_crash_reporting_api_key = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int google_storage_bucket = 2131165200;
			
			// aapt resource value: 0x7f070009
			public const int label_parent_dir = 2131165193;
			
			// aapt resource value: 0x7f070005
			public const int label_parent_directory = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int last_edit = 2131165190;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FilePickerPreference = new int[] {
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 3
			public const int FilePickerPreference_error_dir = 3;
			
			// aapt resource value: 5
			public const int FilePickerPreference_extensions = 5;
			
			// aapt resource value: 4
			public const int FilePickerPreference_offset_dir = 4;
			
			// aapt resource value: 2
			public const int FilePickerPreference_root_dir = 2;
			
			// aapt resource value: 0
			public const int FilePickerPreference_selection_mode = 0;
			
			// aapt resource value: 1
			public const int FilePickerPreference_selection_type = 1;
			
			// aapt resource value: 6
			public const int FilePickerPreference_title_text = 6;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
